version: "2"
services:
  web:
    build: ./web
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - app
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
  php:
    build: ./php
    ports:
      - "9000:9000"
    volumes_from:
      - app
    depends_on:
      - db
  app:
    build: ./app
    volumes:
      - /usr/local/nginx/html
  db:
    image: mysql:5.7.18
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
volumes:
    db-data:
